#include "core/web_bundle.hpp"

#include <gtest/gtest.h>

#include <fstream>
#include <iterator>
#include <vector>

// WEB_BUNDLE_PATH is generated by CMake from the real web/src via tools/pack_web.py.
TEST(WebBundle, ParsesRealUiBundle) {
  std::ifstream in(WEB_BUNDLE_PATH, std::ios::binary);
  const std::vector<uint8_t> data{std::istreambuf_iterator<char>(in), {}};
  ASSERT_FALSE(data.empty());

  auto bundle = core::WebBundle::parse(data);
  ASSERT_TRUE(bundle.has_value());
  EXPECT_EQ(bundle->etag().size(), 16u);

  auto index = bundle->find("index.html");
  ASSERT_TRUE(index.has_value());
  EXPECT_EQ(index->content_type, "text/html; charset=utf-8");
  ASSERT_GE(index->gzip.size(), 2u);
  EXPECT_EQ(index->gzip[0], 0x1F);  // gzip magic
  EXPECT_EQ(index->gzip[1], 0x8B);

  EXPECT_TRUE(bundle->find("app.js").has_value());
  EXPECT_TRUE(bundle->find("icons/logo.svg").has_value());
  EXPECT_FALSE(bundle->find("../secret").has_value());
}

TEST(WebBundle, RejectsCorruptData) {
  const std::vector<uint8_t> bad = {'P', 'C', 'W', 'B', 1};
  EXPECT_FALSE(core::WebBundle::parse(bad).has_value());
  std::vector<uint8_t> truncated = {'P', 'C', 'W', 'B', 1};
  truncated.insert(truncated.end(), 16, 'a');
  truncated.push_back(1);                         // one asset announced…
  truncated.insert(truncated.end(), {3, 'a', 'b'});  // …but its path is cut short
  EXPECT_FALSE(core::WebBundle::parse(truncated).has_value());
}
